spring:
  datasource:
    url: jdbc:postgresql://192.168.1.126:5432/recipe_manager_dev
    username: recipe_manager_dev
    password: recipe_manager_dev
recipe-manager:
  jwt:
    expiration: 3_600_000
    issuer: http://localhost:8080
    secret: helloworld123456789helloworld123456789helloworld123456789